- name: Automate Create Jenkins Jobs
  hosts: localhost
  connection: local
  roles:
    - seed-job
  vars:
    jobs:
      - { name: sample1, repo_name: learn-jenkins}
      - { name: sample2, repo_name: learn-jenkins }
      - { name: sample3, repo_name: learn-jenkins }
      - { name: sample4, repo_name: learn-jenkins }